web/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    sign_up_view,
    sign_up_option_view,
    sign_up_success_view,
    verify_email_view,
    sign_up_complete_view,
    login_view,

    obtain_token,
)

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('sign-up', sign_up_view, name='sign_up'),
    path('sign-up-option', sign_up_option_view, name='sign_up_option'),
    path('sign-up-success', sign_up_success_view, name='sign_up_success'),
    path('verify-email/<str:token>', verify_email_view, name='verify_email'),
    path('sign-up-complete', sign_up_complete_view, name='sign_up_complete'),

    path('oauth/token', obtain_token, name='token'),

]

web/dashboard/urls.py
from django.urls import path

from .views import dashboard_view

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
]

web/tags/urls.py
from django.urls import path

from .views import (
    TagListView,
)

app_name = 'tags'

urlpatterns = [
    path('', TagListView.as_view(), name='list'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import home_view, weblet_detail_view, portal_detail

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home'),
    path('webcast/<str:slug>', weblet_detail_view, name='weblet_detail_view'),
    path('portal_detail', portal_detail, name='portal_detail'),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard', include('dashboard.urls', namespace='dashboard')),
    path('weblets/', include('weblets.urls', namespace='weblets')),
    path('presenters/', include('presenters.urls', namespace='presenters')),
    path('watchers/', include('watchers.urls', namespace='watchers')),
    path('portals/', include('portals.urls', namespace='portals')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('search/', include('search.urls', namespace='search')),

    path('api/weblets/', include('weblets.api.urls', namespace='weblets-api')),
    path('api/portals/', include('portals.api.urls', namespace='portals-api')),
    path('api/tags/', include('tags.urls', namespace='tags')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/web/templates/partials/admin-navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-theme-primary sticky-top">
    <button type="button" id="sidebarCollapse" class="btn btn-sm btn-primary">
        <i class="fas fa-bars"></i>
    </button>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
<!--            {% if request.user.is_authenticated %}-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'settings:home' %}">Hello {{ request.user.email }}</a>-->
<!--            </li>-->
<!--            {% else %}-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'accounts:sign_up' %}">Sign Up</a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>-->
<!--            </li>-->
<!--            {% endif %}-->
        </ul>
    </div>
</nav>

web/web/templates/partials/admin-sidebar.html
{% load static %}

{% url 'dashboard:dashboard' as dashboard_url %}
{% url 'presenters:list' as presenter_list_url %}
{% url 'watchers:list' as watcher_list_url %}
{% url 'weblets:list' as weblet_list_url %}
{% url 'portals:list' as portal_list_url %}
{% url 'analytics:home' as analytics_home_url %}
{% url 'settings:home' as settings_home_url %}

<nav id="sidebar">
    <div class="sidebar-header">
        <a href="{% url 'home' %}">
            <img src="{% static 'assets/main_logo_transparent.png' %}" alt="" class="sidebar-brand">
        </a>
    </div>
    <div class="user-profile">
        <div class="user-profile-body">
            <div>
                {% if request.user.image_file %}
                <img src="{{ request.user.image_file.url }}"
                     class="rounded-circle" alt="...">
                {% else %}
                <img src="/static/assets/default-user.png"
                     class="rounded-circle" alt="...">
                {% endif %}
            </div>
            <div class="dropdown">
                <a href="javascript:void(0)" class="dropdown-toggle u-dropdown link hide-menu"
                   data-toggle="dropdown"
                   role="button" aria-haspopup="true" aria-expanded="false">
                    <span style="font-size: small">
                        {% if request.user.first_name %}
                            {{ request.user.first_name }}
                        {% else %}
                            {{ request.user.email|truncatechars:20 }}
                        {% endif %}
                    </span>
                    <span class="caret"></span>
                </a>
                <div class="dropdown-menu animated swing">
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-user"></i> My Profile
                    </a>
                    <a href="{% url 'settings:home' %}" class="dropdown-item">
                        <i class="fas fa-cogs"></i> Settings
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                        <i class="fas fa-power-off"></i> Logout
                    </a>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <ul class="sidebar-menu">
        <li class="{% if request.path == dashboard_url %}current{% endif %}">
            <a href="{{ dashboard_url }}">
                <i class="fas fa-home sidebar-item-icon"></i> Dashboard
            </a>
        </li>
        <li class="{% if request.path == weblet_list_url %}current{% endif %}">
            <a href="{{ weblet_list_url }}">
                <i class="fas fa-play-circle sidebar-item-icon"></i> Weblets
            </a>
        </li>
        <li class="{% if request.path == presenter_list_url %}current{% endif %}">
            <a href="{{ presenter_list_url }}">
                <i class="fa fa-laptop sidebar-item-icon"></i> Presenters
            </a>
        </li>
        <li class="{% if request.path == watcher_list_url %}current{% endif %}">
            <a href="{{ watcher_list_url }}">
                <i class="fas fa-users sidebar-item-icon"></i> Watchers
            </a>
        </li>
        <li class="{% if request.path == portal_list_url %}current{% endif %}">
            <a href="{{ portal_list_url }}">
                <i class="fas fa-globe sidebar-item-icon"></i> Portals
            </a>
        </li>
        <li class="{% if request.path == analytics_home_url %}current{% endif %}">
            <a href="{{ analytics_home_url }}">
                <i class="fas fa-chart-bar sidebar-item-icon"></i> Analytics
            </a>
        </li>
        <li class="{% if request.path == settings_home_url %}current{% endif %}">
            <a href="{{ settings_home_url }}">
                <i class="fas fa-cogs sidebar-item-icon"></i> Settings
            </a>
        </li>
    </ul>
</nav>

web/web/templates/partials/alert-message.html
{% if messages %}
{% for message in messages %}

<script>console.log('{{message}}');</script>

{% if message.tags == 'success'%}
<script>toastr.success('{{message}}');</script>
{% elif message.tags == 'info'%}
<script>toastr.info('{{message}}');</script>
{% elif message.tags == 'warning'%}
<script>toastr.warning('{{message}}');</script>
{% elif message.tags == 'error'%}
<script>toastr.error('{{message}}');</script>
{% endif %}
{% endfor %}
{% endif %}

web/web/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-theme-primary sticky-top">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'assets/LogoNameAndIconWhite.png' %}" alt="" width="150px">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   style="text-decoration: none; font-size: 13px">
                    {{ request.user.email }}
                </a>
                <div class="dropdown-menu dropdown dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Profile</a>
                    {% if request.user.type == 'admin' or request.user.type == 'author'  %}
                    <a class="dropdown-item" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link mr-1 py-1 btn btn-sm btn-outline-secondary text-white" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link py-1 btn btn-sm btn-secondary text-white" href="{% url 'accounts:sign_up_option' %}">Explore With Us</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>