web/dashboard/urls.py
from django.urls import path

from .views import dashboard_view

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import home_view, weblet_detail_view, portal_detail

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home'),
    path('webcast/<str:slug>', weblet_detail_view, name='weblet_detail_view'),
    path('portal_detail', portal_detail, name='portal_detail'),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard', include('dashboard.urls', namespace='dashboard')),
    path('weblets/', include('weblets.urls', namespace='weblets')),
    path('presenters/', include('presenters.urls', namespace='presenters')),
    path('watchers/', include('watchers.urls', namespace='watchers')),
    path('portals/', include('portals.urls', namespace='portals')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('search/', include('search.urls', namespace='search')),

    path('api/weblets/', include('weblets.api.urls', namespace='weblets-api')),
    path('api/portals/', include('portals.api.urls', namespace='portals-api')),
    path('api/tags/', include('tags.urls', namespace='tags')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/weblets/api/urls.py
from django.urls import path

from .views import (
    manipulate_weblet_presenter
)

app_name = 'weblets-api'

urlpatterns = [
    path('manipulate_weblet_presenter', manipulate_weblet_presenter, name='manipulate_weblet_presenter'),
]

web/weblets/urls.py
from django.urls import path

from .views import (
    WebletListView,
    WebletDetailView,
    WebletCreateView,
    WebletUpdateView,
    WebletDeleteView,

    zoom_import
)

app_name = 'weblets'

urlpatterns = [
    path('', WebletListView.as_view(), name='list'),
    path('<str:slug>/detail', WebletDetailView.as_view(), name='detail'),
    path('create', WebletCreateView.as_view(), name='create'),
    path('<str:slug>/update', WebletUpdateView.as_view(), name='update'),
    path('<str:slug>/delete', WebletDeleteView.as_view(), name='delete'),

    path('zoom/import', zoom_import, name='zoom_import'),
]

web/weblets/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import pre_save

from accounts.models import Account
from web.utils import unique_str_gen
from presenters.models import Presenter

User = settings.AUTH_USER_MODEL

WEBLET_STATUS_ENUM = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    ('deleted', 'Deleted'),
)


def picture_thumbnail_path(instance, filename):
    return 'weblets/{}/thumbnail/{}'.format(instance.title, filename)


def picture_large_path(instance, filename):
    return 'weblets/{}/large/{}'.format(instance.title, filename)


class WebletManager(models.Manager):

    def search(self, query):
        lookups = Q(title__icontains=query) | Q(description__icontains=query) | Q(
            presenters__full_name__icontains=query) | Q(presenters__company_name__icontains=query) | Q(
            tags__icontains=query)
        return self.get_queryset().filter(lookups).distinct()


class Weblet(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, related_name='weblet')
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=10, default='draft', choices=WEBLET_STATUS_ENUM)
    picture_thumbnail = models.ImageField(null=True, blank=True, upload_to=picture_thumbnail_path)
    picture_large = models.ImageField(null=True, blank=True, upload_to=picture_large_path)
    tags = models.TextField(null=True, blank=True)
    webinar_recording_link = models.CharField(max_length=512)
    watcher_signup_required = models.BooleanField(default=False)
    publish_on_lw_website = models.BooleanField(default=False)
    presenters = models.ManyToManyField(Presenter, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    created_on = models.DateTimeField(auto_now=True)
    last_modified_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='weblet_created_by')
    last_modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                         related_name='weblet_modified_by')

    objects = WebletManager()

    class Meta:
        ordering = ('-created_on', '-last_modified_on')

    def __str__(self):
        return self.title

    def get_tags(self):
        tags = self.tags
        if tags:
            return tags.split(',')
        return []


@receiver(pre_save, sender=Weblet)
def weblet_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.slug = unique_str_gen.unique_slug_generator(instance, instance.title)

web/weblets/forms.py
from django import forms

from .models import Weblet


class WebletForm(forms.ModelForm):
    class Meta:
        model = Weblet
        fields = ('title', 'description', 'status', 'picture_thumbnail', 'picture_large', 'tags',
                  'webinar_recording_link', 'watcher_signup_required', 'publish_on_lw_website')
        labels = {
            'publish_on_lw_website': 'Publish on LW website'
        }
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
            'tags': forms.Textarea(attrs={'rows': 3}),
        }

web/weblets/api/views.py
import json
from rest_framework.decorators import api_view
from rest_framework.response import Response

from weblets.models import Weblet
from presenters.models import Presenter


@api_view(['POST'])
def manipulate_weblet_presenter(request):
    weblet_id = request.POST.get('weblet_id')
    weblet = Weblet.objects.get(id=weblet_id)
    presenters = json.loads(request.POST.get('presenters'))
    for _id, status in presenters.items():
        presenter = Presenter.objects.get(id=_id)
        if status:
            weblet.presenters.add(presenter)
        else:
            weblet.presenters.remove(presenter)
    return Response({})

web/weblets/views.py
import json

from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Weblet
from .forms import WebletForm
from .utils import save_weblet
from .services import get_webinars, get_recordings
from presenters.models import Presenter


class WebletListView(LoginRequiredMixin, generic.ListView):
    template_name = 'weblets/list.html'
    paginate_by = 8

    def get_queryset(self):
        return Weblet.objects.filter(account=self.request.user.account)

    def get_context_data(self, *args, **kwargs):
        context = super(WebletListView, self).get_context_data(*args, **kwargs)
        context['page_title'] = 'Weblets'
        context['presenters'] = Presenter.objects.filter(account=self.request.user.account)
        context['weblet_presenter'] = [{weblet.id: [p.id for p in weblet.presenters.all()]} for weblet in
                                       self.get_queryset()]
        return context


class WebletDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'weblets/detail.html'

    def get_queryset(self):
        return Weblet.objects.filter(account=self.request.user.account)

    def get_context_data(self, **kwargs):
        context = super(WebletDetailView, self).get_context_data(**kwargs)
        return context


class WebletCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = WebletForm
    success_url = reverse_lazy('weblets:list')
    template_name = 'weblets/form.html'

    def get_queryset(self):
        return Weblet.objects.filter(account=self.request.user.account)

    def get_context_data(self, **kwargs):
        context = super(WebletCreateView, self).get_context_data(**kwargs)
        context['page_title'] = 'Weblets'
        context['title'] = 'Create'
        return context

    def form_valid(self, form):
        form.instance.account = self.request.user.account
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return super().form_invalid(form)


class WebletUpdateView(LoginRequiredMixin, generic.UpdateView):
    form_class = WebletForm
    success_url = reverse_lazy('weblets:list')
    template_name = 'weblets/form.html'

    def get_queryset(self):
        return Weblet.objects.filter(account=self.request.user.account)

    def get_context_data(self, **kwargs):
        context = super(WebletUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = 'Weblets'
        context['title'] = 'Update'
        return context

    def form_valid(self, form):
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class WebletDeleteView(LoginRequiredMixin, generic.DeleteView):
    success_url = reverse_lazy('weblets:list')
    template_name = 'weblets/delete.html'

    def get_queryset(self):
        return Weblet.objects.filter(account=self.request.user.account)

    def get_context_data(self, **kwargs):
        context = super(WebletDeleteView, self).get_context_data(**kwargs)
        context['page_title'] = 'Weblets'
        return context


def manipulate_weblet_presenter(request):
    weblet_id = request.POST.get('weblet_id')
    weblet = Weblet.objects.get(id=weblet_id)
    presenters = json.loads(request.POST.get('presenters'))
    for _id, status in presenters.items():
        presenter = Presenter.objects.get(id=_id)
        if status:
            weblet.presenters.add(presenter)
        else:
            weblet.presenters.remove(presenter)
    return redirect('weblets:list')


def zoom_import(request):
    context = dict()
    context['page_title'] = 'Weblets'
    token_type = request.session.get('token_type')
    access_token = request.session.get('access_token')

    if token_type and access_token:
        recordings = []
        status_code, json_data = get_webinars('richa.ahuja@livingwebinar.com', token_type, access_token)
        if status_code == 200:
            for w in json_data['webinars']:

                status_code, json_data = get_recordings(w['id'], token_type, access_token)
                if status_code == 200:
                    recording_link = json_data['share_url']
                else:
                    recording_link = ''
                recordings.append({
                    'id': w['id'],
                    'title': w['topic'],
                    'description': w['agenda'],
                    'recording_link': recording_link
                })
            context['webinars'] = recordings
        else:
            context['error'] = json_data['message']
    # context['webinars'] = [
    #     {'id': 1, 'title': 'Title 1', 'description': 'Some Description', 'recording_link': ''},
    #     {'id': 2, 'title': 'Title 2', 'description': 'Some Description', 'recording_link': 'xyz'},
    #     {'id': 3, 'title': 'Title 3', 'description': 'Some Description', 'recording_link': ''},
    #     {'id': 4, 'title': 'Title 4', 'description': 'Some Description', 'recording_link': 'mno'}
    # ]
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        recording_link = request.POST.get('recording_link')
        save_weblet(request.user, title, description, recording_link)
        return HttpResponse('OK')
    return render(request, 'weblets/zoom_import.html', context)

web/web/templates/weblets/delete.html
{% extends 'layouts/author.html' %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{% url 'dashboard:dashboard' %}">
            <i class="fas fa-home"></i> Dashboard
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'weblets:list' %}">
            Weblets
        </a>
    </li>
    <li class="breadcrumb-item active">Delete</li>
</ol>
{% endblock breadcrumb %}

{% block content %}

<div class="row mb-3">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Delete Weblet</h4>
                <h6 class="card-subtitle">
                    Weblets are widgets that will be available for your audience on your own website or
                    LivingWebinar.Com
                </h6>
                <form action="" method="post" class="mt-5">
                    {% csrf_token %}
                    <h5>Are you sure you want to delete "{{ object.title }}" ?</h5>
                    <small>
                        <i class="fas fa-user"></i> {{ object.created_by.email }}
                        <i class="fas fa-calendar-alt ml-3"></i> {{ object.created_on }}
                    </small>
                    <div class="my-4">
                        <a href="{% url 'weblets:list' %}" class="btn btn-sm btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary">Confirm</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

web/web/templates/weblets/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

web/web/templates/weblets/form.html
{% extends 'layouts/author.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block substyle %}
<link rel="stylesheet" href="{% static 'plugins/dropify/css/dropify.min.css' %}">
<style>
    .dropify-wrapper {
        font-size: 13px;
        font-family: 'Poppins', sans-serif;
    }

</style>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{% url 'dashboard:dashboard' %}">
            <i class="fas fa-home"></i> Dashboard
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'weblets:list' %}">
            Weblets
        </a>
    </li>
    <li class="breadcrumb-item active">{{ title }}</li>
</ol>
{% endblock breadcrumb %}

{% block content %}


<div class="row mb-3">
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <h4 class="card-title">{{ title }} Weblet</h4>
                <h6>
                    Weblets are widgets that will be available for your audience on your own website or
                    LivingWebinar.Com
                </h6>
                <form action="" class="mt-4" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form.title|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-5 mb-0">
                            {{ form.webinar_recording_link|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{ form.status|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.tags|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.description|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_picture_thumbnail" class="col-form-label">
                                Picture Thumbnail
                            </label>
                            <input type="file" name="picture_thumbnail" id="id_picture_thumbnail"
                                   class="dropify" accept=".jpg, .png, image/jpeg, image/png">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_picture_large" class="col-form-label">
                                Picture Large
                            </label>
                            <input type="file" name="picture_large" id="id_picture_large"
                                   class="dropify" accept=".jpg, .png, image/jpeg, image/png">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.publish_on_lw_website|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-12">
                            {{ form.watcher_signup_required|as_crispy_field }}
                        </div>
                    </div>
                    <a href="{% url 'weblets:list' %}" class="btn btn-sm btn-secondary">Cancel</a>
                    <button type="submit" class="btn btn-sm btn-primary">{{title}}</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block subscript %}
<script src="{% static 'plugins/dropify/js/dropify.min.js' %}"></script>
<script>

$('#id_picture_thumbnail').dropify();
$('#id_picture_large').dropify();


</script>
{% endblock %}

web/web/templates/weblets/list.html
{% extends 'layouts/author.html' %}

{% block substyle %}
<style>

</style>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
<li class="breadcrumb-item">
    <a href="{% url 'dashboard:dashboard' %}">
        <i class="fas fa-home"></i> Dashboard
    </a>
</li>
<li class="breadcrumb-item active">Weblets</li>
</ol>
<a href="{% url 'weblets:create' %}" class="btn btn-sm btn-secondary shadow-sm ml-3">
    <i class="fa fa-plus-circle"></i> Create New
</a>
<a href="https://zoom.us/oauth/authorize?response_type=code&amp;client_id=2AAjch3rQ0mRQdRZmK4UlA&amp;redirect_uri=http://localhost:8001/accounts/oauth/token"
   target="_blank" rel="noopener noreferrer" class="btn btn-sm btn-secondary shadow-sm ml-1">
    <img src="/static/assets/zoom-logo.jpeg" alt="" height="18px">
</a>
{% endblock breadcrumb %}

{% block content %}

<div class="row mb-3">
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <div>
                        <h4 class="card-title">Showing all Weblets</h4>
                        <h6 class="text-secondary">
                            Weblets are widgets that will be available for your audience on your own website or
                            LivingWebinar.Com
                        </h6>
                    </div>
                    <div>
                        <div class="form-group">
                            <select class="form-control form-control-sm rounded-0">
                                <option>Most Popular</option>
                                <option>Some other</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row mt-3 mb-4">
                    {% for object in object_list %}
                    <div class="col-lg-3">
                        <div class="card shadow mb-3">
                            {% if  object.picture_thumbnail %}
                            <img class="card-img-top" src="{{ object.picture_thumbnail.url }}"
                                 alt="Card image cap" height="150px;">
                            {% else %}
                            <img class="card-img-top" src="/static/assets/ImageNotAvailable.png"
                                 alt="Card image cap" height="150px;">
                            {% endif %}
                            <div class="card-img-overlay pt-2 pr-2 text-right" style="height: 30px">
                                <button class="btn btn-sm btn-primary" data-toggle="modal"
                                        data-target="#addPresenterModal" data-weblet-id="{{object.id}}">
                                    <i class="fas fa-user" data-toggle="tooltip" title="Attach Presenters"></i>
                                </button>
                                <a href="{% url 'weblets:update' object.slug %}"
                                   class="btn btn-sm btn-primary">
                                    <i class="fas fa-pencil-alt" data-toggle="tooltip" title="Update"></i>
                                </a>
                                <a href="{% url 'weblets:delete' object.slug %}"
                                   class="btn btn-sm btn-secondary">
                                    <i class="fas fa-trash" data-toggle="tooltip" title="Delete"></i>
                                </a>
                            </div>
                            <div class="card-body p-3">
                                <h6 class="card-title">{{ object.title|truncatechars:25 }}</h6>
                                <div class="d-flex justify-content-between">
                                    <small>
                                        <i class="fas fa-calendar-alt mr-1"></i>
                                        {{object.created_on}}
                                    </small>
                                    {% if object.watcher_signup_required %}
                                    <i class="fas fa-lock text-theme-primary" data-toggle="tooltip"
                                       title="Watcher Sign Up required"></i>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="d-flex justify-content-center">
                    {% if is_paginated %}
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link">Previous</a>
                        </li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                        <li class="page-item active">
                            <!--<span>{{ i }} <span class="sr-only">(current)</span></span>-->
                            <a href="" class="page-link">{{ i }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link">Next</a>
                        </li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addPresenterModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-theme-primary">
                <h4 class="modal-title text-white">Add Presenter</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                {% if presenters %}
                <ul class="list-group mb-3" id="webletPresenterGroup">
                    {% for presenter in presenters %}
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="media">
                            <img src="/static/img/presenters/default.jpg" class="img-thumbnail mr-3" alt="..."
                                 width="30">
                            <div class="media-body" style="font-size: small">
                                <span class="mt-0">{{presenter.full_name}}</span> <br>
                                <span style="font-size: xx-small">{{presenter.title}}</span>
                            </div>
                        </div>
                        <input type="checkbox" data-presenter-id="{{ presenter.id }}">
                    </li>
                    {% endfor %}
                </ul>
                <button class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                <button class="btn btn-sm btn-primary" id="saveWebletPresenter">Save</button>
                {% else %}
                <div class="my-4 text-center">
                    <small>No presenters are available for this account</small>
                    <br><br>
                    <a href="{% url 'presenters:create' %}" class="btn btn-sm btn-primary">Go to Add Presenter</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block subscript %}
<script>

    let presenters = {};

    let webletPresenterPayload = {
        csrfmiddlewaretoken: "{{ csrf_token }}",
        weblet_id: null,
        presenters: {}
    }

    $('#addPresenterModal').on('show.bs.modal', function(e) {
        let webletId = $(e.relatedTarget).data('weblet-id');
        $('#webletPresenterGroup input[type=checkbox]').each(function() {
            let presenterId = $(this).attr('data-presenter-id');
            $(this).attr('id', `w-${webletId}p-${presenterId}`);
        });

        $('#webletPresenterGroup input[type=checkbox]').attr('data-weblet-id', webletId);

        let weblet_presenter_ids = $.grep({{weblet_presenter}}, function(e) { return e[parseInt(webletId)] });
        let presenter_ids = weblet_presenter_ids[0][webletId];
        $('#webletPresenterGroup input[type=checkbox]').each(function() {
            $(this).attr('checked', false);
        })
        $.each(presenter_ids, function(i, v) {
            $('#w-'+webletId+'p-'+v).attr('checked', true);
        });

        webletPresenterPayload['weblet_id'] = webletId;
    });

    $('#webletPresenterGroup input[type=checkbox]').change(function() {
        let isChecked = $(this).is(":checked");
        let webletId = $(this).attr('data-weblet-id');
        let presenterId = $(this).attr('data-presenter-id');
        webletPresenterPayload['weblet_id'] = webletId;
        presenters[presenterId] = isChecked;
    });

    $('#saveWebletPresenter').click(function() {
        webletPresenterPayload['presenters'] = JSON.stringify(presenters);
        presenters= {};
        $.ajax({
            type: "POST",
            url: "/api/weblets/manipulate_weblet_presenter",
            data: webletPresenterPayload,
            success: function() {
                window.location.href = window.location.href;
            },
            dataType: 'json'
        });
    });











</script>
{% endblock %}